### PR TITLE
move .ta to own dir and enlighten opteetree to load .ta file from host when called from container

### PR DESCRIPTION
**Pull request by seanmcd-msft**

### CODE REVIEW

**Comment by dmcilvaney** [comment]
Do we know if anyone is loading TAs from inside Windows these days? I expect this would break that flow.

Shouldn't affect any of the firmware launched TAs though.

**Comment by seanmcd-msft** [comment]
> Do we know if anyone is loading TAs from inside Windows these days? I expect this would break that flow.
> Shouldn't affect any of the firmware launched TAs though.
I've discussed this with Asher. I assume you're referring to changing the load directory? since the rest only affects containers which don't work yet anyway.  putting random non-inbox stuff in system32 is problematic for several reasons and the sooner we change that the less legacy we have to deal with.  opteetree isn't being used in any shipping products afaik.  asher said he didn't know of any either.  if i'm wrong about that we should discuss this more when I get back from vacation. and, in the meantime you should take the rest of the change or take the change and revert that one line :)

**Comment by dmcilvaney** [comment]
Unless @Britel remembers, I'll ask Dave Thaler when I get in on Monday, as I recall him grumbling about some related stuff last year. I think it was mostly to do with needing to register TAs in the registry, but doesn't hurt to ask.

**Comment by Britel** [comment]
Yes - it was the requirement to register the TA in some hive, when you already need system access to be able to install the TA on the system in the first place. The registry entry was argued to be un-necessary.

**Comment by seanmcd-msft** [comment]
I have this crazy notion i discussed with jiri and asher this morning that we should either install them like drivers through the pnp stack or install a fixed loader TA service at image creation that's analogous to linux /dev/t0 and not register any of the dynamic ones and just load on the fly via a file path.  but, that's a complicated discussion with a number of pro's and con's and different implications for iot core vs. enterprise.  however, currently you have to reboot to install any new one which is not flexible and seems bad to me. so, we should definitely investigate further improvements here.

**Review by dmcilvaney — APPROVED** [review]

**Pull request merged**
